// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iylyzckrakrpoddamwml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bHl6Y2tyYWtycG9kZGFtd21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTcxNjgsImV4cCI6MjA2MzA5MzE2OH0.jy8IwzHGQ8HpRNrIyAbBPH6oi8oyGcvY43ig0G016Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);